services:
  myportfolio:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/myportfolio
    depends_on:
      - mysql

  mysql:
    image: mariadb
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase:
